export {default as Navbar} from './navbar/Navbar';
export {default as Toparticles} from './toparticles/Toparticles';
export {default as Slider} from './sliderr/Slider';
export {default as Allarticles} from './allarticles/Allarticles';
export {default as Stats} from './stats/Stats';
export {default as Footer} from './footer/Footer';
export {default as Lastsection} from './lastsection/Lastsection';
export {default as WriteArticle} from './writeArticle/WriteArticle';
export {default as Article} from './article/Article';
